FROM python:3.10-slim

WORKDIR /app

# Install operating system dependencies required for compilation tasks
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy dependencies manifest definitions file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy binary assets and operational source modules
COPY app/main.py ./app/
COPY COPY term_deposit_model.pkl .
COPY scaler.pkl .

EXPOSE 8000

# Fire up managed high performance web server runtime interface instance
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]